fix: capsule-proxy should proxy users who owns multiple tenants. Remove v1beta1 ingress version
clastix/capsule-proxy pull request #298
Opened 2023-05-22 23:05 UTC by MaxFedotov

this PR closes #297 and also removes support for v1beta1 ingress version, as it is considered obsolete.

2023-05-23 08:02 UTC, prometherion requested changes
I see a lot of changes in this MR, such as deprecating the support of the `v1beta1` group.

I'd ask you to create smaller changes at the commit level, and possibly, open the discussion for these drops of support in a separate MR.

I'm feeling good about the changes introduced on the `HandleListSelector`, let's go one by one to simplify the review, too.

2023-05-23 08:02 UTC, prometherion commented on internal/modules/metric/list.go
> +		log:    ctrl.Log.WithName("metrics_get"),
Shouldn't be `metrics_list`?

2023-05-23 08:02 UTC, prometherion commented on internal/modules/ingressclass/get.go
> +	return "/apis/networking.k8s.io/v1/{endpoint:ingressclasses}/{name}"
If we go only for `v1` it means we're gonna drop support for `v1beta1`:

```
// +k8s:prerelease-lifecycle-gen:introduced=1.18
// +k8s:prerelease-lifecycle-gen:deprecated=1.19
```

If this is the case, we should document it properly by marking the commit according to the conventional commits annotations.

I'm open for discussion, surely, however, I wouldn't address such a big change while addressing a bug, unless it's related to it.

2023-05-23 15:15 UTC, MaxFedotov commented
@prometherion, WDYT if I split this PR into 3 parts:
1) deprecating ingress v1beta1
2) refactoring error handling
3) fix for list\get

2023-05-26 11:05 UTC, MaxFedotov commented on internal/modules/metric/list.go
> +		log:    ctrl.Log.WithName("metrics_get"),
done

2023-05-26 11:05 UTC, MaxFedotov commented on internal/modules/ingressclass/get.go
> +	return "/apis/networking.k8s.io/v1/{endpoint:ingressclasses}/{name}"
rollbacked this change

2023-05-26 11:06 UTC, MaxFedotov commented
@prometherion split the commit into 2 separate and rollbacked all changes related to ingressclasses v1beta1 deprication

2023-06-01 13:31 UTC, merged