Using kubeconfig to access the kubernetes api
clastix/capsule-proxy pull request #68
Opened 2021-03-17 17:47 UTC by ludusrusso

This PR Closes #67 and allow the connection to kubernetes using kubectl files.

## Changes

1. `k8s-control-plane-url` cmd option is no more required, the url is directly got from kubeconfig
2.  Authentication to k8s is done using certificates from kubeconfig. It should work with a bearerToken provided by kubeconfig file but I didn't test it

## Usage

```bash
go run main.go --ssl-cert-path=/tmp/localhost.pem --ssl-key-path=/tmp/localhost-key.pem  --kubeconfig=./config.kub --enable-ssl=true
```

## Tests

I've manually tested with kind and I'm able to get nemespaces kubernetes api. @prometherion when tests are ready we should run this against automated tests before merging.

2021-03-17 18:31 UTC, ludusrusso commented
Thinking about it, we cannot skip completely bearer token! Sorry I'm tired :D

2021-03-17 20:19 UTC, prometherion commented
> Bearer token authentication is used but in my option we do not need it anymore, @prometherion what do you think?

The token is mandatory for the in cluster mode since the Service Account token is used to authenticate against the API Server.

2021-03-17 20:23 UTC, davideimola commented
As I said to @ludusrusso, I think we can cause a breaking changes while removing the flag `--k8s-control-plane-url` if someone uses custom configs.

What do you think @prometherion and @bsctl ?

2021-03-18 07:47 UTC, bsctl commented
> As I said to @ludusrusso, I think we can cause a breaking changes while removing the flag `--k8s-control-plane-url` if someone uses custom configs.

@ludusrusso that option is used in the sidecar scenario and removing it is a breaking change. Please take care, we have currently the proxy in production.

2021-03-18 07:51 UTC, prometherion commented
> @ludusrusso that option is used in the sidecar scenario and removing it is a breaking change. Please take care, we have currently the proxy in production.

The feature is planned for 0.1.0 and it will be breaking change.

The issue with the commit is that we don't have to edit the Helm Chart options until the 0.1.0 release hasn't yet published: said so, please, drop the commit, otherwise the CI wll publish a new Helm Chart release that will be broken (we've already faced in Capsule).

2021-03-18 07:57 UTC, ludusrusso commented
> > As I said to @ludusrusso, I think we can cause a breaking changes while removing the flag `--k8s-control-plane-url` if someone uses custom configs.
> 
> @ludusrusso that option is used in the sidecar scenario and removing it is a breaking change. Please take care, we have currently the proxy in production.

Yes! I understand this. What is the best for you? Actually the options is no more required since it is automatically loaded by `rest.GetConfigOrDie()` function. I just read the kubernetes url from `config` instead of from the option, and it is loaded correctly both in cluster and out of cluster.

The problem here is that if you call the program with a option that is not configured in `flag` will make the program fails, as in capsule/issues/232

So now if I leave the options in chart the chart will fails. We have two option:
1. Leave the option  both in chart and in code but ignore it
2. Leave the option both in chart and in code and, if present, use it instead of the one coming from config.

What do you prefer?

2021-03-18 12:43 UTC, prometherion commented
We'll deal with the chart once releasing 0.1.0, we have to consider the main branch (actually, `master`) as the development one.

Said so, let's ignore the chart update as well removing the CLI flag `--k8s-control-plane-url`.

2021-03-18 12:46 UTC, prometherion commented
> Said so, let's ignore the chart update as well removing the CLI flag --k8s-control-plane-url.

Ok, said a stupid thing: let's mark the flag as deprecated, otherwise, the Helm chart would break upon installation during the CI.

We're going to open an issue to remove the deprecated flag on 0.1.0 release: this will require a little more effort on your side @ludusrusso since it means allowing also the deprecated way, hope you can understand.

2021-03-18 13:01 UTC, prometherion requested changes

2021-03-18 13:01 UTC, prometherion commented on main.go
> -	k8sControlPlaneUrl := flag.String("k8s-control-plane-url", "https://kubernetes.default.svc", "Kubernetes control plane URL (default: https://kubernetes.default.svc)")
We have to keep this for backward compatibility, planning to remove starting from 0.1.0.

Let's default to an empty string and add a log informing the end-user we're going to deprecate this in the upcoming release. If the value is provided we'll use it.

2021-03-18 13:03 UTC, prometherion requested changes

2021-03-18 13:03 UTC, prometherion commented on internal/options/kube.go
> +	"k8s.io/client-go/transport"
Imports statement is not sorted: should be placed in the underlying block along with `k8s.io/client-go/rest`

2021-03-18 13:04 UTC, ludusrusso commented
> > Said so, let's ignore the chart update as well removing the CLI flag --k8s-control-plane-url.
> 
> Ok, said a stupid thing: let's mark the flag as deprecated, otherwise, the Helm chart would break upon installation during the CI.
> 
> We're going to open an issue to remove the deprecated flag on 0.1.0 release: this will require a little more effort on your side @ludusrusso since it means allowing also the deprecated way, hope you can understand.

No problem for that. So, If I've got it correctly:

1. I leave the `k8s-control-plane-url` flag in code as "deprecated". 
2. So in case the flag is passed as cmd line option, I'll use it in place of `k.config.Host`.
3. I do not change the Charts now! But
4. I remove the flag from yaml spec!

I'm not sure how to deprecate the flag. I was thinking on adding a log in case the user is using it and change the description in 
 `Kubernetes control plane URL (DEPRECATED)`. Is there a better way?
 
 Thanks for the help!

2021-03-18 13:29 UTC, prometherion commented
> 1. I leave the `k8s-control-plane-url` flag in code as "deprecated".
> 2. So in case the flag is passed as cmd line option, I'll use it in place of `k.config.Host`.
> 3. I do not change the Charts now! But
> 4. I remove the flag from yaml spec!

If you're referring to the Charts values, we have to keep it.

> I'm not sure how to deprecate the flag. I was thinking on adding a log in case the user is using it and change the description in
> `Kubernetes control plane URL (DEPRECATED)`. Is there a better way?

It's good enough, thanks!

2021-03-18 13:32 UTC, ludusrusso commented
> If you're referring to the Charts values, we have to keep it.
> 
> >

Nono, I mean from pure k8s files `deploy/*yaml`

2021-03-18 13:48 UTC, prometherion commented
> I mean from pure k8s files `deploy/*.yaml`

Let's keep them, we'll tackle them along with the Helm release.

2021-03-18 16:43 UTC, prometherion requested changes
Final change requests but I think we can merge this!

Just a little remark, although non documented: could you amend commits following the semantic commit message styleguide?

Something as:

```
doc: running capsule locally
refactor!: transport configuration from k8s REST configuration
```

Obviously, commit subjects are just an example, feel free to edit at your wish since you're the author!

2021-03-18 16:43 UTC, prometherion commented on internal/options/kube.go
> +// TODO: Remove k8sControlPlaneUrl
`TODO`s are something I really hate in code: we can ignore it since we're already tracking with #71 :)

2021-03-18 16:43 UTC, prometherion commented on main.go
> +	// TODO: Remove k8s-control-plane-url
Same here, already tracking on #71.

2021-03-18 16:51 UTC, ludusrusso commented on main.go
> +	// TODO: Remove k8s-control-plane-url
Ok sorry for that!

2021-03-18 17:04 UTC, ludusrusso commented
> Final change requests but I think we can merge this!
> 
> Just a little remark, although non documented: could you amend commits following the semantic commit message styleguide?
> 
> Something as:
> 
> ```
> doc: running capsule locally
> refactor!: transport configuration from k8s REST configuration
> ```
> 
> Obviously, commit subjects are just an example, feel free to edit at your wish since you're the author!

Now should be ok!

2021-03-18 17:50 UTC, prometherion approved these changes
LGTM! Thanks for your effort @ludusrusso! 🚀

2021-03-18 17:50 UTC, merged